# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Update the VM
    apt-get update
    apt-get -y upgrade
    apt-get -y dist-upgrade

    # Add vim and vim customization
    apt-get install -y vim
    git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
    sh ~/.vim_runtime/install_awesome_vimrc.sh

    # Install project deps
    apt-get install -y python3 python3-pip python3-dev
    apt-get install -y npm

    # Install Node deps
    npm install -g n
    n install latest
  SHELL

end