#!/usr/bin/env sh

# check if `node` is available, if not, print an error message and exit
if ! command -v node > /dev/null 2>&1; then
  echo "Error: Node.js is not installed or not in PATH." >&2
  exit 1
fi

# check if NODE_OPTIONS is set. If it is set, print a warning message
if [ -n "$NODE_OPTIONS" ]; then
  echo "Warning: NODE_OPTIONS is already set to '$NODE_OPTIONS'. Appending to it." >&2
fi

# check if DYNAJS_HOME is set. If it is not set, print an error message and exit
if [ -z "$DYNAJS_HOME" ]; then
  echo "Error: DYNAJS_HOME is not set. Please set it to the repository root of dynajs." >&2
  exit 1
fi

# check if DYNAJS_OPTIONS is set. If it is not set, print a warning message
if [ -z "$DYNAJS_OPTIONS" ]; then
  echo "Warning: DYNAJS_OPTIONS is not set. run \`dynajs\` for usage information." >&2
fi

IMPORT_OPT="--import $DYNAJS_HOME/dist/entry/import.js"

COMBINED_NODE_OPTIONS="${NODE_OPTIONS:+$NODE_OPTIONS }$IMPORT_OPT${DYNAJS_NODE_OPTIONS_POST:+ $DYNAJS_NODE_OPTIONS_POST}"

# if no arguments are provided AND DYNAJS_OPTIONS is not set, use `node` to print the help message
if [ "$#" -eq 0 ] && [ -z "$DYNAJS_OPTIONS" ]; then
  DYNAJS_OPTIONS="--help" NODE_OPTIONS="$COMBINED_NODE_OPTIONS" node
else
  NODE_OPTIONS="$COMBINED_NODE_OPTIONS" "$@"
fi